[pytest]
# Directorio raíz de los archivos .feature para pytest-bdd
bdd_features_base_dir = features/

# Descubre los tests en la carpeta steps/
testpaths = steps

# Marcadores personalizados (opcional)
markers =
    caso_nuevo: Tests de registro de caso nuevo (TC-01 a TC-05)
    accion_academica: Tests de acción académica (TC-06 a TC-13)
    sancion: Tests de sanción académica (TC-14 a TC-18)
