# Generated by Django 5.2.12 on 2026-05-03 22:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('legal_deadline', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Activo'), ('Pendiente', 'Pendiente'), ('Asignado', 'Asignado'), ('En proceso', 'En proceso')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='accounts.beneficiary')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='accounts.professor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='accounts.legalroom')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_cases', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'caso',
            },
        ),
        migrations.CreateModel(
            name='AcademicAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('document', 'Entrega de documento'), ('followup', 'Seguimiento'), ('attendance', 'Asistencia a cita')], max_length=20)),
                ('grade', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('observation', models.TextField(blank=True, default='')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('document_delivered', models.BooleanField(blank=True, null=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_actions', to='accounts.professor')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_actions', to='cases.case')),
            ],
            options={
                'verbose_name': 'Academic Action',
                'verbose_name_plural': 'Academic Actions',
                'db_table': 'accion_academica',
            },
        ),
        migrations.CreateModel(
            name='CaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('asignacion', 'Asignación'), ('reasignacion', 'Reasignación'), ('sancion', 'Sanción'), ('error_notificacion', 'Error de notificación')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='cases.case')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Log',
                'verbose_name_plural': 'Case Logs',
                'db_table': 'bitacora_caso',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeWeightConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('weight_documents', models.IntegerField()),
                ('weight_followups', models.IntegerField()),
                ('weight_attendance', models.IntegerField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_configs', to='accounts.professor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_configs', to='accounts.legalroom')),
            ],
            options={
                'verbose_name': 'Grade Weight Config',
                'verbose_name_plural': 'Grade Weight Configs',
                'db_table': 'configuracion_pesos',
                'unique_together': {('professor', 'room', 'period')},
            },
        ),
    ]
