# Generated by Django 5.2.12 on 2026-05-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('Pendiente', 'Pendiente'), ('Asignado', 'Asignado'), ('En proceso', 'En proceso'), ('Cerrado', 'Cerrado')], default='active', max_length=20),
        ),
    ]
