# Generated by Django 5.2.12 on 2026-05-17 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_appointment_appointmentlog_communicationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecordTraceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('ANNUL_ATTEMPT', 'Annul attempt')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traceability_records', to='cases.academicaction')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_record_traceability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Record Traceability',
                'verbose_name_plural': 'Academic Record Traceabilities',
                'db_table': 'trazabilidad_registro_academico',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
