# Generated by Django 5.2.12 on 2026-05-17 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_academicrecordtraceability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicaction',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULLED', 'Annulled')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_attempted', models.CharField(max_length=100)),
                ('record_id', models.CharField(max_length=100)),
                ('result', models.CharField(choices=[('BLOCKED', 'Blocked')], max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'db_table': 'bitacora_sistema',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
