# Generated by Django 5.2.12 on 2026-05-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_automatic_assignment_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselog',
            name='event_type',
            field=models.CharField(choices=[('asignacion', 'Asignación'), ('reasignacion', 'Reasignación'), ('sancion', 'Sanción'), ('error_notificacion', 'Error de notificación'), ('notificacion_recordatorio', 'Notificación de recordatorio')], max_length=30),
        ),
    ]
