# Generated by Django 5.2.12 on 2026-04-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolechangelog',
            options={'verbose_name': 'Role Change Log', 'verbose_name_plural': 'Role Change Logs'},
        ),
        migrations.AlterModelOptions(
            name='secretary',
            options={'verbose_name': 'Secretary', 'verbose_name_plural': 'Secretaries'},
        ),
        migrations.AlterModelTable(
            name='rolechangelog',
            table='bitacora_roles',
        ),
        migrations.AlterModelTable(
            name='secretary',
            table='secretaria',
        ),
    ]
